### PR TITLE
reformat code according to psr-2

### PR DESCRIPTION
**Pull request by dmitry-mukhin**
this is what left:

```
1.45s$ php vendor/bin/phpcs --standard=PSR2 src
FILE: .../build/uploadcare/uploadcare-php/src/Uploadcare/FileIterator.php
----------------------------------------------------------------------
FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  6 | WARNING | Method name "_pd_getDataChunk" should not be prefixed
    |         | with an underscore to indicate visibility
  6 | ERROR   | Method name "FileIterator::_pd_getDataChunk" is not
    |         | in camel caps format
 11 | WARNING | Method name "_pd_GetCount" should not be prefixed
    |         | with an underscore to indicate visibility
 11 | ERROR   | Method name "FileIterator::_pd_GetCount" is not in
    |         | camel caps format
----------------------------------------------------------------------
FILE: ...build/uploadcare/uploadcare-php/src/Uploadcare/GroupIterator.php
----------------------------------------------------------------------
FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  6 | WARNING | Method name "_pd_getDataChunk" should not be prefixed
    |         | with an underscore to indicate visibility
  6 | ERROR   | Method name "GroupIterator::_pd_getDataChunk" is not
    |         | in camel caps format
 11 | WARNING | Method name "_pd_GetCount" should not be prefixed
    |         | with an underscore to indicate visibility
 11 | ERROR   | Method name "GroupIterator::_pd_GetCount" is not in
    |         | camel caps format
----------------------------------------------------------------------
FILE: ...d/uploadcare/uploadcare-php/src/Uploadcare/PagedDataIterator.php
----------------------------------------------------------------------
FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 185 | WARNING | Method name "_pd_getDataChunk" should not be
     |         | prefixed with an underscore to indicate visibility
 185 | ERROR   | Method name "PagedDataIterator::_pd_getDataChunk" is
     |         | not in camel caps format
 211 | WARNING | Method name "_pd_GetCount" should not be prefixed
     |         | with an underscore to indicate visibility
 211 | ERROR   | Method name "PagedDataIterator::_pd_GetCount" is not
     |         | in camel caps format
----------------------------------------------------------------------
FILE: ...e/travis/build/uploadcare/uploadcare-php/src/Uploadcare/File.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | WARNING | Line exceeds 120 characters; contains 150 characters
----------------------------------------------------------------------
Time: 1.37 secs; Memory: 18.5Mb
```

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
@ZNick1982 take a look if those changes are OK (at leasts tests pass :)
and if we can easily cater to the last errors/warnings (see description).

**Comment by kbsali** [comment]
+1 for reformatting all this to follow PSR-2! But how about using php-cs-fixer for this?
I'd be happy to propose a PR, but is this going to be considered/accepted? :)

**Comment by kbsali** [comment]
+1 for reformatting the code to follow PSR2,
but how about using php-cs-fixer to automate this?
I'm happy to propose a PR for doing this, but is it going to be considered/accepted? :)

**Comment by dmitry-mukhin** [comment]
everything will be considered :)

**Pull request closed without merging**
