### PR TITLE
Add more context to the UUID not found exception

### PR DESCRIPTION
**Pull request by kbsali**
We are getting the "UUID not found" exception regularly, but no context is given, so have have to add this on the client's side...

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
What kind of context are you having in mind?

**Comment by kbsali** [comment]
just what my PR does : give the uuid_or_url in the message! :)
to make it easier to investigate

**Comment by dmitry-mukhin** [comment]
oh, sorry didn't see that was a PR :)

you're right, but I think it's better to change the error message in this case to something more verbose like
"you have to provide UUID or CDN URL, %s doesn't match the pattern"

**Comment by kbsali** [comment]
how about
```php
      throw new \Exception(sprintf('Wrong UUID or CDN URL format [provided "%s"]', $uuid_or_url));
```
?

**Comment by dmitry-mukhin** [comment]
well, of there's garbage, you can't tell that it's in the wrong format.
So, "UUID or CDN URL cannot be found in '%s'" works better.

**Comment by dmitry-mukhin** [comment]
thanks!

**Pull request merged**
