### PR TITLE
Allow to use guzzlehttp/psr7:^2

### PR DESCRIPTION
**Pull request by newtype0092**
## Description

Add Guzzle PSR-7 version 2.x to resolve some dependency conflicts.

Thanks.

## Checklist

- [x] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

### CODE REVIEW

**Comment by rsedykh** [comment]
Hi. Sorry on missing out on this PR.

Have you tested backward compatibility? Will something break if you change major version?

**Comment by newtype0092** [comment]
Sure, all unit test passes and it works fine on my project. 😄

**Comment by Casmo** [comment]
Would be nice!

**Comment by rsedykh** [comment]
Hey. Can you create auto-test for this PR? To run it in both environments and check that nothing brakes?

**Comment by amsoell** [comment]
Is approval of this PR on the horizon? I'm considering using Uploadcare on a production Laravel project, but the latest version of Laravel uses Guzzle PSR-7 version 2.x

**Comment by rsedykh** [comment]
@amsoell hi. https://github.com/uploadcare/uploadcare-php/releases/tag/v3.2.4 Thank you for using Uploadcare. :-)

**Pull request merged**
